---
abstract: 'module for managing simple, temporary, easy mailing lists'
author:
  - 'chromatic <chromatic@wgz.org>'
build_requires:
  Test::Exception: '0'
  Test::MockObject: '1.07'
  Test::Simple: '0.47'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4218, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-SimpleList
provides:
  Mail::SimpleList:
    file: lib/Mail/SimpleList.pm
    version: '0.94'
  Mail::SimpleList::Alias:
    file: lib/Mail/SimpleList/Alias.pm
    version: '0.94'
  Mail::SimpleList::Aliases:
    file: lib/Mail/SimpleList/Aliases.pm
    version: '0.94'
requires:
  Class::Roles: '0.30'
  Email::MIME: '1.937'
  Mail::Action: '0.42'
  Mail::Internet: '1.53'
  Pod::Simple: '0'
  YAML: '0.35'
resources:
  license: http://dev.perl.org/licenses/
version: '0.94'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
