--- #YAML:1.0
name: Mail-SimpleList
version: 0.81
license: perl
distribution_type: module
requires:
  Mail::Address: 1.53
  Mail::Internet: 1.53
  Pod::Simple: ''
  Test::Exception: ''
  Test::MockObject: 0.11
  Test::Simple: 0.47
  YAML: 0.35
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Mail::SimpleList:
    file: lib/Mail/SimpleList.pm
    version: 0.81
  Mail::SimpleList::Alias:
    file: lib/Mail/SimpleList/Alias.pm
    version: 0.81
  Mail::SimpleList::Aliases:
    file: lib/Mail/SimpleList/Aliases.pm
    version: 0.81
  Mail::SimpleList::PodToHelp:
    file: lib/Mail/SimpleList/PodToHelp.pm
generated_by: Module::Build version 0.20
