--- #YAML:1.0
name: Mail-SimpleList
version: 0.70
license: perl
distribution_type: module
requires:
  Mail::Address: 1.53
  Mail::Internet: 1.53
  Test::Exception: ''
  Test::MockObject: 0.11
  Test::Simple: 0.47
  YAML: 0.35
recommends: {}
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.16
